openapi: 3.0.0
info:
  title: Event Management API
  version: 1.0.0
  description: API documentation for the Event Management System
servers:
  - url: https://event-planning-l5he.onrender.com/api
paths: {}
components: {}
tags: []
